version: '2'

volumes:
  data:
  db:

services:
# mariaDB Container
  db:
    image: mariadb:11.1.1-rc
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
# It is strongly recommended to change these identifiers by other more secure ones.
# Don't forget to report them in the app service below.
      - MYSQL_ROOT_PASSWORD=rtpsw
      - MYSQL_PASSWORD=psw
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=user
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 5s
      retries: 3

#GLPI Container
  app:
    image: jr0w3/glpi
    restart: always
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./app:/app
    environment:
      - MYSQL_PASSWORD=psw
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=user
      - MYSQL_HOST=db
    healthcheck:
      test: ["CMD", "curl", "http://localhost", "-f"]
      interval: 5s
      timeout: 5s
      retries: 24
